// <auto-generated />
using System;
using Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    [Migration("20220221201501_EducationMigrationInicial")]
    partial class EducationMigrationInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Education.Domain.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = new Guid("2a010d37-448d-4e5d-b5f3-46fd4920c6e8"),
                            DataCriacao = new DateTime(2022, 2, 21, 17, 15, 1, 218, DateTimeKind.Local).AddTicks(6797),
                            DataPublicacao = new DateTime(2024, 2, 21, 17, 15, 1, 218, DateTimeKind.Local).AddTicks(6807),
                            Descricao = "Curso C# Basic",
                            Preco = 56m,
                            Titulo = "C# do 0 ao avançado"
                        },
                        new
                        {
                            CursoId = new Guid("3bfc679c-5345-41ff-91ba-5e4e8e8af286"),
                            DataCriacao = new DateTime(2022, 2, 21, 17, 15, 1, 218, DateTimeKind.Local).AddTicks(6839),
                            DataPublicacao = new DateTime(2024, 2, 21, 17, 15, 1, 218, DateTimeKind.Local).AddTicks(6839),
                            Descricao = "Curso Java",
                            Preco = 25m,
                            Titulo = "Master in Java Springs desde as raizes"
                        },
                        new
                        {
                            CursoId = new Guid("4120f8c1-10e5-497e-8652-8e3ddac68ef4"),
                            DataCriacao = new DateTime(2022, 2, 21, 17, 15, 1, 218, DateTimeKind.Local).AddTicks(6843),
                            DataPublicacao = new DateTime(2024, 2, 21, 17, 15, 1, 218, DateTimeKind.Local).AddTicks(6844),
                            Descricao = "Curso de Unit Test para Net Core",
                            Preco = 1000m,
                            Titulo = "Master in Unit Test com CQRS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
